#!/usr/bin/env bash
# Create an IoT Thing, certificate, and scoped policy. Writes PEM files + certs.h snippet.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
REGION="${AWS_REGION:-ap-southeast-2}"
THING_NAME="${THING_NAME:-esp32-c61-01}"
POLICY_NAME="${POLICY_NAME:-iot-talk-${THING_NAME}-policy}"
OUT_DIR="${OUT_DIR:-$ROOT/out/${THING_NAME}}"
ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"

mkdir -p "$OUT_DIR"

echo "Region=$REGION Thing=$THING_NAME Out=$OUT_DIR"

if ! aws iot describe-thing --thing-name "$THING_NAME" --region "$REGION" >/dev/null 2>&1; then
  aws iot create-thing --thing-name "$THING_NAME" --region "$REGION" >/dev/null
  echo "Created Thing $THING_NAME"
else
  echo "Thing $THING_NAME already exists"
fi

CERT_ARN_FILE="$OUT_DIR/certificate-arn.txt"
if [[ -f "$CERT_ARN_FILE" ]]; then
  CERT_ARN="$(cat "$CERT_ARN_FILE")"
  echo "Reusing certificate $CERT_ARN"
else
  aws iot create-keys-and-certificate \
    --set-as-active \
    --certificate-pem-outfile "$OUT_DIR/device.pem.crt" \
    --public-key-outfile "$OUT_DIR/device.public.key" \
    --private-key-outfile "$OUT_DIR/device.private.key" \
    --region "$REGION" \
    --query certificateArn \
    --output text >"$CERT_ARN_FILE"
  CERT_ARN="$(cat "$CERT_ARN_FILE")"
  echo "Created certificate $CERT_ARN"
fi

# Amazon Root CA 1
if [[ ! -f "$OUT_DIR/AmazonRootCA1.pem" ]]; then
  curl -fsSL "https://www.amazontrust.com/repository/AmazonRootCA1.pem" -o "$OUT_DIR/AmazonRootCA1.pem"
fi

POLICY_DOC=$(cat <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:Connect",
      "Resource": "arn:aws:iot:${REGION}:${ACCOUNT_ID}:client/${THING_NAME}"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Publish",
      "Resource": [
        "arn:aws:iot:${REGION}:${ACCOUNT_ID}:topic/devices/${THING_NAME}/telemetry",
        "arn:aws:iot:${REGION}:${ACCOUNT_ID}:topic/devices/${THING_NAME}/events"
      ]
    }
  ]
}
EOF
)

if aws iot get-policy --policy-name "$POLICY_NAME" --region "$REGION" >/dev/null 2>&1; then
  aws iot create-policy-version \
    --policy-name "$POLICY_NAME" \
    --policy-document "$POLICY_DOC" \
    --set-as-default \
    --region "$REGION" >/dev/null
  echo "Updated policy $POLICY_NAME"
else
  aws iot create-policy \
    --policy-name "$POLICY_NAME" \
    --policy-document "$POLICY_DOC" \
    --region "$REGION" >/dev/null
  echo "Created policy $POLICY_NAME"
fi

aws iot attach-policy --policy-name "$POLICY_NAME" --target "$CERT_ARN" --region "$REGION" >/dev/null || true
aws iot attach-thing-principal --thing-name "$THING_NAME" --principal "$CERT_ARN" --region "$REGION" >/dev/null || true

ENDPOINT="$(aws iot describe-endpoint --endpoint-type iot:Data-ATS --region "$REGION" --query endpointAddress --output text)"
echo "$ENDPOINT" >"$OUT_DIR/iot-endpoint.txt"

# Emit certs.h for firmware (escape PEM newlines)
python3 - "$OUT_DIR" <<'PY'
import pathlib, sys
out = pathlib.Path(sys.argv[1])

def pem_c_string(path: pathlib.Path) -> str:
    text = path.read_text().strip() + "\n"
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'

ca = pem_c_string(out / "AmazonRootCA1.pem")
crt = pem_c_string(out / "device.pem.crt")
key = pem_c_string(out / "device.private.key")
header = f'''#ifndef CERTS_H
#define CERTS_H

// Generated by demo/aws/provision-thing.sh — do not commit.

static const char AWS_CERT_CA[] = {ca};

static const char AWS_CERT_CRT[] = {crt};

static const char AWS_CERT_PRIVATE[] = {key};

#endif  // CERTS_H
'''
(out / "certs.h").write_text(header)
print(f"Wrote {out / 'certs.h'}")
PY

FIRMWARE_INCLUDE="$(cd "$ROOT/../firmware/include" && pwd)"
cp "$OUT_DIR/certs.h" "$FIRMWARE_INCLUDE/certs.h"
echo "Copied certs.h → $FIRMWARE_INCLUDE/certs.h"
echo
echo "Next:"
echo "  1. Copy config.example.h → config.h and set WIFI_* , THING_NAME=$THING_NAME,"
echo "     AWS_IOT_ENDPOINT=$ENDPOINT"
echo "  2. Run ./deploy-stack.sh (ingest + query)"
echo "  3. Flash firmware and open the Amplify dashboard"
